name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - id: deploy 
      name: Deploy to Cloud Run
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: 'no-bs-site'
        source: '.'
        region: ${{ secrets.GCP_REGION }}

    - name: 'Deployed to Cloud Run'
      run: echo "Deployed to Cloud Run at ${{ steps.deploy.outputs.url }}"
